### ISSUE TITLE
Codecov upload failed

### ISSUE THREAD

**Issue by vmx** [ipfs-inactive/dev-team-enablement#154]
## Which Project is this about?

js-ipld-dag-cbor

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/blue/organizations/jenkins/IPLD%2Fjs-ipld-dag-cbor/detail/PR-82/2/pipeline/

The code coverage upload to Codeconv didn't work as the response from the API was empty:

```
[IPLD_js-ipld-dag-cbor_PR-82-E5LEXJEZALKWQSOTCCIKHRGHFH2BNTTSTJU7ZFBHVHTV5M4MQG7Q@2] Running shell script
+ curl --silent https://codecov.io/api/gh/ipld/js-ipld-dag-cbor?access_token=****
+ node -e let data = '';process.stdin.on('data', (d) => data = data + d.toString());process.stdin.on('end', () => console.log(JSON.parse(data).repo.upload_token));
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.process.stdin.on ([eval]:1:122)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
script returned exit code 1
```

**Comment by vmx** [comment]
Hasn't happened in a long time for me. I'll re-open if it happens again.
